### ISSUE TITLE
Identity Switch slow refresh

### ISSUE THREAD

**Issue by wesch3al** [toteph42/identity_switch#50]
I setup Identity Switch and it is working but refresh is slow. Also, it throws errors saying not able to connect to server. I just do a manual refresh. This is what the log file says.

#0 F:\Xampp\htdocs\plugins\identity_switch\identity_switch_newmails.php(88): fclose(Object(identity_switch_rpc))
#1 F:\Xampp\htdocs\plugins\identity_switch\identity_switch_newmails.php(223): identity_switch_newmails->run()
#2 {main}
  thrown in F:\Xampp\htdocs\plugins\identity_switch\identity_switch_newmails.php on line 88

**Comment by wesch3al** [comment]
Here is the full error, it happens when I bring Roundcube up.

[15-Dec-2024 07:51:17 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type resource, identity_switch_rpc given in F:\Xampp\htdocs\plugins\identity_switch\identity_switch_newmails.php:88
Stack trace:
#0 F:\Xampp\htdocs\plugins\identity_switch\identity_switch_newmails.php(88): fclose(Object(identity_switch_rpc))
#1 F:\Xampp\htdocs\plugins\identity_switch\identity_switch_newmails.php(223): identity_switch_newmails->run()
#2 {main}
  thrown in F:\Xampp\htdocs\plugins\identity_switch\identity_switch_newmails.php on line 88

**Comment by toteph42** [comment]
Hi,
if you get error when connecting to a server, then you should in first place adjust your configuration parameters or this identity. the `fclose()` error only happens, if no connection could properly be established.
You may use `identy_switch` logging or debugging and at least the configuration options in `config/config.inc.php`:

`// Log IMAP conversation to <log_dir>/imap.log or to syslog`
`$config['imap_debug'] = true;`

I'll fix the `fclose()` error in an upcoming version. More I cannot do for you.

**Comment by wesch3al** [comment]
Here is the identity switch log;

[17-Dec-2024 20:44:27 +0100]: <ivcpsi2r> Switching to identity "willie@oakdraft.com"
[17-Dec-2024 20:44:29 +0100]: <ivcpsi2r> Starting new mail check with arguments "a:3:{s:4:"task";s:4:"mail";s:6:"action";s:9:"getunread";s:5:"abort";b:0;}"."
[17-Dec-2024 20:44:29 +0100]: <ivcpsi2r> Configuration loaded "a:10:{s:7:"logging";b:1;s:5:"check";b:1;s:8:"interval";i:300;s:5:"delay";i:0;s:7:"retries";i:10;s:5:"debug";b:1;s:8:"language";s:5:"en_US";s:5:"cache";s:69:"F:\Xampp\htdocs\temp/identity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:4:"data";s:67:"F:\Xampp\htdocs\temp/identity_switch_ret.ivcpsi2rhii08r57vmh4a8hodf";s:2:"fp";O:19:"identity_switch_rpc":3:{s:25:" identity_switch_rpc host";s:9:"localhost";s:24:" identity_switch_rpc req";s:145:"/plugins/identity_switch/identity_switch_newmails.php?iid=0&cache=F%3A%5CXampp%5Chtdocs%5Ctemp%2Fidentity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:23:" identity_switch_rpc fp";i:0;}}".
[17-Dec-2024 20:44:29 +0100]: <ivcpsi2r> Check allowed for 4 account(s)
[17-Dec-2024 20:44:35 +0100]: <ivcpsi2r> No data file exist - stop checking
[17-Dec-2024 20:45:29 +0100]: <ivcpsi2r> Starting new mail check with arguments "a:3:{s:4:"task";s:4:"mail";s:6:"action";s:7:"refresh";s:5:"abort";b:0;}"."
[17-Dec-2024 20:45:29 +0100]: <ivcpsi2r> Configuration loaded "a:10:{s:7:"logging";b:1;s:5:"check";b:1;s:8:"interval";i:300;s:5:"delay";i:0;s:7:"retries";i:10;s:5:"debug";b:1;s:8:"language";s:5:"en_US";s:5:"cache";s:69:"F:\Xampp\htdocs\temp/identity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:4:"data";s:67:"F:\Xampp\htdocs\temp/identity_switch_ret.ivcpsi2rhii08r57vmh4a8hodf";s:2:"fp";O:19:"identity_switch_rpc":3:{s:25:" identity_switch_rpc host";s:9:"localhost";s:24:" identity_switch_rpc req";s:145:"/plugins/identity_switch/identity_switch_newmails.php?iid=0&cache=F%3A%5CXampp%5Chtdocs%5Ctemp%2Fidentity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:23:" identity_switch_rpc fp";i:0;}}".
[17-Dec-2024 20:45:29 +0100]: <ivcpsi2r> Check allowed for 5 account(s)
[17-Dec-2024 20:45:30 +0100]: <ivcpsi2r> No data file exist - stop checking
[17-Dec-2024 20:46:30 +0100]: <ivcpsi2r> No data file exist - stop checking
[17-Dec-2024 20:46:39 +0100]: <ivcpsi2r> Starting new mail check with arguments "a:3:{s:4:"task";s:4:"mail";s:6:"action";s:7:"refresh";s:5:"abort";b:0;}"."
[17-Dec-2024 20:46:39 +0100]: <ivcpsi2r> Configuration loaded "a:10:{s:7:"logging";b:1;s:5:"check";b:1;s:8:"interval";i:300;s:5:"delay";i:0;s:7:"retries";i:10;s:5:"debug";b:1;s:8:"language";s:5:"en_US";s:5:"cache";s:69:"F:\Xampp\htdocs\temp/identity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:4:"data";s:67:"F:\Xampp\htdocs\temp/identity_switch_ret.ivcpsi2rhii08r57vmh4a8hodf";s:2:"fp";O:19:"identity_switch_rpc":3:{s:25:" identity_switch_rpc host";s:9:"localhost";s:24:" identity_switch_rpc req";s:145:"/plugins/identity_switch/identity_switch_newmails.php?iid=0&cache=F%3A%5CXampp%5Chtdocs%5Ctemp%2Fidentity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:23:" identity_switch_rpc fp";i:0;}}".
[17-Dec-2024 20:46:39 +0100]: <ivcpsi2r> Check allowed for 5 account(s)
[17-Dec-2024 20:47:40 +0100]: <ivcpsi2r> No data file exist - stop checking
[17-Dec-2024 20:47:49 +0100]: <ivcpsi2r> Starting new mail check with arguments "a:3:{s:4:"task";s:4:"mail";s:6:"action";s:7:"refresh";s:5:"abort";b:0;}"."
[17-Dec-2024 20:47:49 +0100]: <ivcpsi2r> Configuration loaded "a:10:{s:7:"logging";b:1;s:5:"check";b:1;s:8:"interval";i:300;s:5:"delay";i:0;s:7:"retries";i:10;s:5:"debug";b:1;s:8:"language";s:5:"en_US";s:5:"cache";s:69:"F:\Xampp\htdocs\temp/identity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:4:"data";s:67:"F:\Xampp\htdocs\temp/identity_switch_ret.ivcpsi2rhii08r57vmh4a8hodf";s:2:"fp";O:19:"identity_switch_rpc":3:{s:25:" identity_switch_rpc host";s:9:"localhost";s:24:" identity_switch_rpc req";s:145:"/plugins/identity_switch/identity_switch_newmails.php?iid=0&cache=F%3A%5CXampp%5Chtdocs%5Ctemp%2Fidentity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:23:" identity_switch_rpc fp";i:0;}}".
[17-Dec-2024 20:47:49 +0100]: <ivcpsi2r> Check allowed for 5 account(s)
[17-Dec-2024 20:48:50 +0100]: <ivcpsi2r> No data file exist - stop checking
[17-Dec-2024 20:48:59 +0100]: <ivcpsi2r> Starting new mail check with arguments "a:3:{s:4:"task";s:4:"mail";s:6:"action";s:7:"refresh";s:5:"abort";b:0;}"."
[17-Dec-2024 20:48:59 +0100]: <ivcpsi2r> Configuration loaded "a:10:{s:7:"logging";b:1;s:5:"check";b:1;s:8:"interval";i:300;s:5:"delay";i:0;s:7:"retries";i:10;s:5:"debug";b:1;s:8:"language";s:5:"en_US";s:5:"cache";s:69:"F:\Xampp\htdocs\temp/identity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:4:"data";s:67:"F:\Xampp\htdocs\temp/identity_switch_ret.ivcpsi2rhii08r57vmh4a8hodf";s:2:"fp";O:19:"identity_switch_rpc":3:{s:25:" identity_switch_rpc host";s:9:"localhost";s:24:" identity_switch_rpc req";s:145:"/plugins/identity_switch/identity_switch_newmails.php?iid=0&cache=F%3A%5CXampp%5Chtdocs%5Ctemp%2Fidentity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:23:" identity_switch_rpc fp";i:0;}}".
[17-Dec-2024 20:48:59 +0100]: <ivcpsi2r> Check allowed for 5 account(s)
[17-Dec-2024 20:49:36 +0100]: <ivcpsi2r> Switching to identity "willie@oakdraft.com"
[17-Dec-2024 20:49:36 +0100]: <ivcpsi2r> Starting new mail check with arguments "a:3:{s:4:"task";s:4:"mail";s:6:"action";s:9:"getunread";s:5:"abort";b:0;}"."
[17-Dec-2024 20:49:36 +0100]: <ivcpsi2r> Configuration loaded "a:10:{s:7:"logging";b:1;s:5:"check";b:1;s:8:"interval";i:300;s:5:"delay";i:0;s:7:"retries";i:10;s:5:"debug";b:1;s:8:"language";s:5:"en_US";s:5:"cache";s:69:"F:\Xampp\htdocs\temp/identity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:4:"data";s:67:"F:\Xampp\htdocs\temp/identity_switch_ret.ivcpsi2rhii08r57vmh4a8hodf";s:2:"fp";O:19:"identity_switch_rpc":3:{s:25:" identity_switch_rpc host";s:9:"localhost";s:24:" identity_switch_rpc req";s:145:"/plugins/identity_switch/identity_switch_newmails.php?iid=0&cache=F%3A%5CXampp%5Chtdocs%5Ctemp%2Fidentity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:23:" identity_switch_rpc fp";i:0;}}".
[17-Dec-2024 20:49:36 +0100]: <ivcpsi2r> Check allowed for 4 account(s)
[17-Dec-2024 20:49:43 +0100]: <ivcpsi2r> Switching to identity "submit@oakdraft.com"
[17-Dec-2024 20:49:43 +0100]: <ivcpsi2r> Starting new mail check with arguments "a:3:{s:4:"task";s:4:"mail";s:6:"action";s:9:"getunread";s:5:"abort";b:0;}"."
[17-Dec-2024 20:49:43 +0100]: <ivcpsi2r> Configuration loaded "a:10:{s:7:"logging";b:1;s:5:"check";b:1;s:8:"interval";i:300;s:5:"delay";i:0;s:7:"retries";i:10;s:5:"debug";b:1;s:8:"language";s:5:"en_US";s:5:"cache";s:69:"F:\Xampp\htdocs\temp/identity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:4:"data";s:67:"F:\Xampp\htdocs\temp/identity_switch_ret.ivcpsi2rhii08r57vmh4a8hodf";s:2:"fp";O:19:"identity_switch_rpc":3:{s:25:" identity_switch_rpc host";s:9:"localhost";s:24:" identity_switch_rpc req";s:145:"/plugins/identity_switch/identity_switch_newmails.php?iid=0&cache=F%3A%5CXampp%5Chtdocs%5Ctemp%2Fidentity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:23:" identity_switch_rpc fp";i:0;}}".
[17-Dec-2024 20:49:43 +0100]: <ivcpsi2r> Check allowed for 3 account(s)
[17-Dec-2024 20:50:00 +0100]: <ivcpsi2r> No data file exist - stop checking
[17-Dec-2024 20:50:38 +0100]: <ivcpsi2r> No data file exist - stop checking
[17-Dec-2024 20:50:43 +0100]: <ivcpsi2r> Starting new mail check with arguments "a:3:{s:4:"task";s:4:"mail";s:6:"action";s:7:"refresh";s:5:"abort";b:0;}"."
[17-Dec-2024 20:50:43 +0100]: <ivcpsi2r> Configuration loaded "a:10:{s:7:"logging";b:1;s:5:"check";b:1;s:8:"interval";i:300;s:5:"delay";i:0;s:7:"retries";i:10;s:5:"debug";b:1;s:8:"language";s:5:"en_US";s:5:"cache";s:69:"F:\Xampp\htdocs\temp/identity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:4:"data";s:67:"F:\Xampp\htdocs\temp/identity_switch_ret.ivcpsi2rhii08r57vmh4a8hodf";s:2:"fp";O:19:"identity_switch_rpc":3:{s:25:" identity_switch_rpc host";s:9:"localhost";s:24:" identity_switch_rpc req";s:145:"/plugins/identity_switch/identity_switch_newmails.php?iid=0&cache=F%3A%5CXampp%5Chtdocs%5Ctemp%2Fidentity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:23:" identity_switch_rpc fp";i:0;}}".
[17-Dec-2024 20:50:43 +0100]: <ivcpsi2r> Check allowed for 4 account(s)
[17-Dec-2024 20:50:45 +0100]: <ivcpsi2r> No data file exist - stop checking
[17-Dec-2024 20:51:45 +0100]: <ivcpsi2r> No data file exist - stop checking
[17-Dec-2024 20:51:53 +0100]: <ivcpsi2r> Starting new mail check with arguments "a:3:{s:4:"task";s:4:"mail";s:6:"action";s:7:"refresh";s:5:"abort";b:0;}"."
[17-Dec-2024 20:51:53 +0100]: <ivcpsi2r> Configuration loaded "a:10:{s:7:"logging";b:1;s:5:"check";b:1;s:8:"interval";i:300;s:5:"delay";i:0;s:7:"retries";i:10;s:5:"debug";b:1;s:8:"language";s:5:"en_US";s:5:"cache";s:69:"F:\Xampp\htdocs\temp/identity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:4:"data";s:67:"F:\Xampp\htdocs\temp/identity_switch_ret.ivcpsi2rhii08r57vmh4a8hodf";s:2:"fp";O:19:"identity_switch_rpc":3:{s:25:" identity_switch_rpc host";s:9:"localhost";s:24:" identity_switch_rpc req";s:145:"/plugins/identity_switch/identity_switch_newmails.php?iid=0&cache=F%3A%5CXampp%5Chtdocs%5Ctemp%2Fidentity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:23:" identity_switch_rpc fp";i:0;}}".
[17-Dec-2024 20:51:53 +0100]: <ivcpsi2r> Check allowed for 4 account(s)
[17-Dec-2024 20:52:55 +0100]: <ivcpsi2r> No data file exist - stop checking
[17-Dec-2024 20:53:05 +0100]: <ivcpsi2r> Starting new mail check with arguments "a:3:{s:4:"task";s:4:"mail";s:6:"action";s:7:"refresh";s:5:"abort";b:0;}"."
[17-Dec-2024 20:53:05 +0100]: <ivcpsi2r> Configuration loaded "a:10:{s:7:"logging";b:1;s:5:"check";b:1;s:8:"interval";i:300;s:5:"delay";i:0;s:7:"retries";i:10;s:5:"debug";b:1;s:8:"language";s:5:"en_US";s:5:"cache";s:69:"F:\Xampp\htdocs\temp/identity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:4:"data";s:67:"F:\Xampp\htdocs\temp/identity_switch_ret.ivcpsi2rhii08r57vmh4a8hodf";s:2:"fp";O:19:"identity_switch_rpc":3:{s:25:" identity_switch_rpc host";s:9:"localhost";s:24:" identity_switch_rpc req";s:145:"/plugins/identity_switch/identity_switch_newmails.php?iid=0&cache=F%3A%5CXampp%5Chtdocs%5Ctemp%2Fidentity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:23:" identity_switch_rpc fp";i:0;}}".
[17-Dec-2024 20:53:05 +0100]: <ivcpsi2r> Check allowed for 4 account(s)
[17-Dec-2024 20:54:06 +0100]: <ivcpsi2r> No data file exist - stop checking
[17-Dec-2024 20:54:34 +0100]: <ivcpsi2r> Starting new mail check with arguments "a:3:{s:4:"task";s:4:"mail";s:6:"action";s:7:"refresh";s:5:"abort";b:0;}"."
[17-Dec-2024 20:54:34 +0100]: <ivcpsi2r> Configuration loaded "a:10:{s:7:"logging";b:1;s:5:"check";b:1;s:8:"interval";i:300;s:5:"delay";i:0;s:7:"retries";i:10;s:5:"debug";b:1;s:8:"language";s:5:"en_US";s:5:"cache";s:69:"F:\Xampp\htdocs\temp/identity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:4:"data";s:67:"F:\Xampp\htdocs\temp/identity_switch_ret.ivcpsi2rhii08r57vmh4a8hodf";s:2:"fp";O:19:"identity_switch_rpc":3:{s:25:" identity_switch_rpc host";s:9:"localhost";s:24:" identity_switch_rpc req";s:145:"/plugins/identity_switch/identity_switch_newmails.php?iid=0&cache=F%3A%5CXampp%5Chtdocs%5Ctemp%2Fidentity_switch_cache.ivcpsi2rhii08r57vmh4a8hodf";s:23:" identity_switch_rpc fp";i:0;}}".
[17-Dec-2024 20:54:34 +0100]: <ivcpsi2r> Check allowed for 4 account(s)

**Comment by toteph42** [comment]
Hi,
as I already pointed out - you habe a problem login into the IMAP server. If `identity_switch` does not get any response within 60 seconds from background checking program, it stops working: `No data file exist - stop checking`. 

You need to trace RoundCube to check which configuration you have to use for logging in to IMAP server. If you can log in with your main account, it may be a good idea, to disable `identity_switch plugin and trace IMAP login of your main account in RoundCube. There you may discover working configuration which you then can use for `identity_switch identities.

**Comment by wesch3al** [comment]
I deleted the identity switch plugin and loaded a clean version; everything seems to be working fine. No more constant refresh and response time has improved. Will see how it runs now. Thanks for the help.

**Comment by wesch3al** [comment]
toteph42,
I realized that when I have the "check new mail = true" I get a looping refresh. I believe that is the bug we talked about.

[19-Dec-2024 05:27:28 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type resource, identity_switch_rpc given in F:\Xampp\htdocs\plugins\identity_switch\identity_switch_newmails.php:88
Stack trace:
#0 F:\Xampp\htdocs\plugins\identity_switch\identity_switch_newmails.php(88): fclose(Object(identity_switch_rpc))
#1 F:\Xampp\htdocs\plugins\identity_switch\identity_switch_newmails.php(223): identity_switch_newmails->run()
#2 {main}
  thrown in F:\Xampp\htdocs\plugins\identity_switch\identity_switch_newmails.php on line 88

I just set the "check mail = false" for a work around. I can use the newmail notifier plugin, until you are able to fix the fclose().
If you remember, send me an email when the bug is fixed. Your plugin is why I am using Roundcube. Thanks for all your work!

**Comment by toteph42** [comment]
The `fclose()` error only happens, if the new mail check fails. So it is definitely a problem of connection parameter too IMAP server.

**Comment by wesch3al** [comment]
Hi,
All 5 of my emails are working. (I have new mail check = false.) Are you saying I have a configuration problem?

**Comment by toteph42** [comment]
Yes,
add 
`// Log IMAP conversation to <log_dir>/imap.log or to syslog`
`$config['imap_debug'] = false;`
`// Log session authentication errors to <log_dir>/session or to syslog`
`$config['log_session'] = false;`

to your RoundCube configuration file `config/config.inc.php` and check log files. There you should see which configuration RoundCube is using.

**Comment by wesch3al** [comment]
Hi,
I disabled the plugin newmail_notifier.
In config.inc.php I set $config['imap_debug'] = false $config['log_session'} = false.
In the identity_switch plugin, I set check new mail to = true.
No errors in the errors.log.

**Comment by wesch3al** [comment]
Hi,
In preferences settings there are no settings for:

Newmail refresh 1min, 5min etc.

Browser notifications test
Desktop notifications test
Sound notification test

**Comment by toteph42** [comment]
Log message states, that there is a connection problem on IMAP connection.

To trace this down:

1. Enable plugin
2. Enable debugging on IMAP connection in RoundCube
3. Switch to the identity which does not work properly
4. Check how RoundCube is trying to connect to IMAP (stored in separate logs)
5. Adjust your `identity_switch` settings for this identity until RoundCube does not raise any error

If you want to change refresh time, go to `User Interface` -> `Refresh (check for new messages, etc.)`

**Comment by wesch3al** [comment]
All emails are working.
All settings are the same on each email except password.
3 Blue Host load fast.
1 Gmail & 1 Yahoo load slow.
If I set plugin to check new mail the refresh gets stuck, does not end.
If I disable check new email the refresh works fine, refreshing every 60 sec.

**Comment by toteph42** [comment]
Added configuration parameter `wait` in plugin configuration file in version 1.1.5.

**Comment by wesch3al** [comment]
Hi,
Loaded V1.1.7 and plugin runs better now.
No more FClose() error.
Can enable - check new mail = true - and refresh is fast and does not hang, closes normally.
In preferences all Identity_Switch categories are present now. 
I do get a PHP warning, don't know if it is important.

[24-Dec-2024 19:40:51 Europe/Berlin] PHP Warning:  Undefined variable $id in F:\Xampp\htdocs\plugins\identity_switch\identity_switch_newmails.php on line 88
[24-Dec-2024 19:40:51 Europe/Berlin] PHP Warning:  Undefined array key "" in F:\Xampp\htdocs\plugins\identity_switch\identity_switch_newmails.php on line 88

Thanks for updating plugin.

**Comment by wesch3al** [comment]
I spoke too soon.
After re-starting Roundcube errors are back.

[24-Dec-2024 22:18:21 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type resource, identity_switch_rpc given in F:\Xampp\htdocs\plugins\identity_switch\identity_switch.php:523
Stack trace:
#0 F:\Xampp\htdocs\plugins\identity_switch\identity_switch.php(523): fclose(Object(identity_switch_rpc))
#1 F:\Xampp\htdocs\program\lib\Roundcube\rcube_plugin_api.php(520): identity_switch->check_newmails(Array)
#2 F:\Xampp\htdocs\program\include\rcmail.php(228): rcube_plugin_api->exec_hook('ready', Array)
#3 F:\Xampp\htdocs\index.php(278): rcmail->action_handler()
#4 {main}
  thrown in F:\Xampp\htdocs\plugins\identity_switch\identity_switch.php on line 523

**Comment by toteph42** [comment]
Hi,
still the same problem:  Connection to host could not properly being established (configuration problem). Added some more checks to prevent resources form being fclosed() in version 1.1.8

**Comment by wesch3al** [comment]
Hi,
I downloaded V1.1.8 and installed.
Seems like all settings for preferences are there now.
 I see no refresh pop-up now at bottom right of screen.
I am sending you the log files.
I don't know what they are telling me.
[errors.log](https://github.com/user-attachments/files/18247014/errors.log)
[imap.log](https://github.com/user-attachments/files/18247015/imap.log)

**Comment by toteph42** [comment]
Fixed another typo in 1.1.9

If google for error message, you'll find something like: https://stackoverflow.com/questions/13445932/php-fopen-failed-to-open-stream-resource-temporarily-unavailable

**Comment by wesch3al** [comment]
I updated to V1.1.13 and could not get it to work?
V1.1.12 works fine - Roundcube seems to refresh much faster.
Maybe something you did in one of the latest versions - haven't updated in
a while.

**Comment by wesch3al** [comment]
Toteph42,

I noticed your "composer.json" file has a tipo for the homepage url, also
you are not putting the "version" in the file so I can tell the version
installed.
I just loaded 1.1.14 and it fixes the problems with 1.1.13 - good job.
